// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_DRIVER_MODE_H
#define UI_DRIVER_MODE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Driver_Mode
extern void ui_Driver_Mode_screen_init(void);
extern void ui_Driver_Mode_screen_destroy(void);
extern lv_obj_t * ui_Driver_Mode;
extern lv_obj_t * ui_rpmbar;
extern lv_obj_t * ui_battbar;
extern lv_obj_t * ui_rpmcontainer;
extern lv_obj_t * ui_rpm;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_lightcontainer;
extern lv_obj_t * ui_kill;
extern lv_obj_t * ui_stall;
extern lv_obj_t * ui_batt;
extern lv_obj_t * ui_heat;
extern lv_obj_t * ui_gearcontainer;
extern lv_obj_t * ui_gear;
extern lv_obj_t * ui_speedcontainer;
extern lv_obj_t * ui_speed;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_laptimercontainer;
extern lv_obj_t * ui_laptimer;
extern lv_obj_t * ui_coolantcontainer;
extern lv_obj_t * ui_coolant;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_gpscontainer;
extern lv_obj_t * ui_maplabel;
extern lv_obj_t * ui_map;
extern lv_obj_t * ui_gforcelabel;
extern lv_obj_t * ui_gforce;
extern lv_obj_t * ui_gpslabel;
extern lv_obj_t * ui_gps;
extern lv_obj_t * ui_voltslabel;
extern lv_obj_t * ui_volts;
extern void ui_event_engrbutton(lv_event_t * e);
extern lv_obj_t * ui_engrbutton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

