// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Driver_Mode = NULL;
lv_obj_t * ui_rpmbar = NULL;
lv_obj_t * ui_battbar = NULL;
lv_obj_t * ui_rpmcontainer = NULL;
lv_obj_t * ui_rpm = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_lightcontainer = NULL;
lv_obj_t * ui_kill = NULL;
lv_obj_t * ui_stall = NULL;
lv_obj_t * ui_batt = NULL;
lv_obj_t * ui_heat = NULL;
lv_obj_t * ui_gearcontainer = NULL;
lv_obj_t * ui_gear = NULL;
lv_obj_t * ui_speedcontainer = NULL;
lv_obj_t * ui_speed = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_laptimercontainer = NULL;
lv_obj_t * ui_laptimer = NULL;
lv_obj_t * ui_coolantcontainer = NULL;
lv_obj_t * ui_coolant = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_gpscontainer = NULL;
lv_obj_t * ui_maplabel = NULL;
lv_obj_t * ui_map = NULL;
lv_obj_t * ui_gforcelabel = NULL;
lv_obj_t * ui_gforce = NULL;
lv_obj_t * ui_gpslabel = NULL;
lv_obj_t * ui_gps = NULL;
lv_obj_t * ui_voltslabel = NULL;
lv_obj_t * ui_volts = NULL;
lv_obj_t * ui_engrbutton = NULL;
// event funtions
void ui_event_engrbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Engineer_Mode, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Engineer_Mode_screen_init);
    }
}

// build funtions

void ui_Driver_Mode_screen_init(void)
{
    ui_Driver_Mode = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Driver_Mode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Driver_Mode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Driver_Mode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmbar = lv_slider_create(ui_Driver_Mode);
    lv_slider_set_value(ui_rpmbar, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_rpmbar) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_rpmbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_rpmbar, 800);
    lv_obj_set_height(ui_rpmbar, 40);
    lv_obj_set_x(ui_rpmbar, 0);
    lv_obj_set_y(ui_rpmbar, -220);
    lv_obj_set_align(ui_rpmbar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_rpmbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmbar, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_rpmbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmbar, lv_color_hex(0x21C400), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_rpmbar, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmbar, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_battbar = lv_slider_create(ui_Driver_Mode);
    lv_slider_set_value(ui_battbar, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_battbar) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_battbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_battbar, 800);
    lv_obj_set_height(ui_battbar, 21);
    lv_obj_set_x(ui_battbar, 0);
    lv_obj_set_y(ui_battbar, 230);
    lv_obj_set_align(ui_battbar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_battbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_battbar, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_battbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_battbar, lv_color_hex(0xF000FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_battbar, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battbar, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_rpmcontainer = lv_obj_create(ui_Driver_Mode);
    lv_obj_remove_style_all(ui_rpmcontainer);
    lv_obj_set_width(ui_rpmcontainer, 279);
    lv_obj_set_height(ui_rpmcontainer, 152);
    lv_obj_set_x(ui_rpmcontainer, 260);
    lv_obj_set_y(ui_rpmcontainer, -124);
    lv_obj_set_align(ui_rpmcontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rpmcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_rpmcontainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rpmcontainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rpmcontainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpm = lv_label_create(ui_rpmcontainer);
    lv_obj_set_width(ui_rpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rpm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpm, "0");
    lv_obj_set_style_text_color(ui_rpm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpm, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_rpmcontainer);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 120);
    lv_obj_set_y(ui_Label13, -35);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "R");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_rpmcontainer);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 120);
    lv_obj_set_y(ui_Label15, 0);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "P");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_rpmcontainer);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 120);
    lv_obj_set_y(ui_Label16, 35);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "M");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightcontainer = lv_obj_create(ui_Driver_Mode);
    lv_obj_remove_style_all(ui_lightcontainer);
    lv_obj_set_width(ui_lightcontainer, 279);
    lv_obj_set_height(ui_lightcontainer, 152);
    lv_obj_set_x(ui_lightcontainer, 260);
    lv_obj_set_y(ui_lightcontainer, 25);
    lv_obj_set_align(ui_lightcontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lightcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_lightcontainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lightcontainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lightcontainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kill = lv_label_create(ui_lightcontainer);
    lv_obj_set_width(ui_kill, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kill, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kill, -65);
    lv_obj_set_y(ui_kill, -40);
    lv_obj_set_align(ui_kill, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kill, "   KILL   ");
    lv_obj_set_style_text_color(ui_kill, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kill, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_kill, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_kill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stall = lv_label_create(ui_lightcontainer);
    lv_obj_set_width(ui_stall, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stall, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stall, -65);
    lv_obj_set_y(ui_stall, 30);
    lv_obj_set_align(ui_stall, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stall, " STALL ");
    lv_obj_set_style_text_color(ui_stall, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_stall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_stall, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_stall, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batt = lv_label_create(ui_lightcontainer);
    lv_obj_set_width(ui_batt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batt, 70);
    lv_obj_set_y(ui_batt, -40);
    lv_obj_set_align(ui_batt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batt, "  BATT  ");
    lv_obj_set_style_text_color(ui_batt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_batt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_batt, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_batt, lv_color_hex(0xFF8A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_batt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heat = lv_label_create(ui_lightcontainer);
    lv_obj_set_width(ui_heat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_heat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_heat, 70);
    lv_obj_set_y(ui_heat, 30);
    lv_obj_set_align(ui_heat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_heat, "  HEAT  ");
    lv_obj_set_style_text_color(ui_heat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_heat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_heat, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_heat, lv_color_hex(0xFF8A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_heat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gearcontainer = lv_obj_create(ui_Driver_Mode);
    lv_obj_remove_style_all(ui_gearcontainer);
    lv_obj_set_width(ui_gearcontainer, 250);
    lv_obj_set_height(ui_gearcontainer, 254);
    lv_obj_set_x(ui_gearcontainer, 0);
    lv_obj_set_y(ui_gearcontainer, -26);
    lv_obj_set_align(ui_gearcontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gearcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_gearcontainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gearcontainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_gearcontainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gear = lv_label_create(ui_gearcontainer);
    lv_obj_set_width(ui_gear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gear, 0);
    lv_obj_set_y(ui_gear, -5);
    lv_obj_set_align(ui_gear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gear, "N");
    lv_obj_set_style_text_color(ui_gear, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gear, &ui_font_GEAR_FONT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedcontainer = lv_obj_create(ui_Driver_Mode);
    lv_obj_remove_style_all(ui_speedcontainer);
    lv_obj_set_width(ui_speedcontainer, 277);
    lv_obj_set_height(ui_speedcontainer, 152);
    lv_obj_set_x(ui_speedcontainer, -262);
    lv_obj_set_y(ui_speedcontainer, -124);
    lv_obj_set_align(ui_speedcontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_speedcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_speedcontainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_speedcontainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_speedcontainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speed = lv_label_create(ui_speedcontainer);
    lv_obj_set_width(ui_speed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_speed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speed, "0");
    lv_obj_set_style_text_color(ui_speed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speed, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_speedcontainer);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -120);
    lv_obj_set_y(ui_Label3, -50);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "S");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_speedcontainer);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -120);
    lv_obj_set_y(ui_Label17, 0);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "E");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_speedcontainer);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -120);
    lv_obj_set_y(ui_Label19, 25);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "E");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_speedcontainer);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -120);
    lv_obj_set_y(ui_Label18, -25);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "P");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_speedcontainer);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -117);
    lv_obj_set_y(ui_Label20, 50);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "D");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_laptimercontainer = lv_obj_create(ui_Driver_Mode);
    lv_obj_remove_style_all(ui_laptimercontainer);
    lv_obj_set_width(ui_laptimercontainer, 247);
    lv_obj_set_height(ui_laptimercontainer, 50);
    lv_obj_set_x(ui_laptimercontainer, 0);
    lv_obj_set_y(ui_laptimercontainer, -175);
    lv_obj_set_align(ui_laptimercontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_laptimercontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_laptimercontainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_laptimercontainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_laptimercontainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_laptimer = lv_label_create(ui_laptimercontainer);
    lv_obj_set_width(ui_laptimer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_laptimer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_laptimer, -4);
    lv_obj_set_y(ui_laptimer, 0);
    lv_obj_set_align(ui_laptimer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_laptimer, "+00:00:00");
    lv_obj_set_style_text_color(ui_laptimer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_laptimer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_laptimer, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coolantcontainer = lv_obj_create(ui_Driver_Mode);
    lv_obj_remove_style_all(ui_coolantcontainer);
    lv_obj_set_width(ui_coolantcontainer, 277);
    lv_obj_set_height(ui_coolantcontainer, 152);
    lv_obj_set_x(ui_coolantcontainer, -262);
    lv_obj_set_y(ui_coolantcontainer, 25);
    lv_obj_set_align(ui_coolantcontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_coolantcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_coolantcontainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_coolantcontainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_coolantcontainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coolant = lv_label_create(ui_coolantcontainer);
    lv_obj_set_width(ui_coolant, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_coolant, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_coolant, 0);
    lv_obj_set_y(ui_coolant, -2);
    lv_obj_set_align(ui_coolant, LV_ALIGN_CENTER);
    lv_label_set_text(ui_coolant, "Lo");
    lv_obj_set_style_text_color(ui_coolant, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_coolant, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_coolant, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_coolantcontainer);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -117);
    lv_obj_set_y(ui_Label1, 40);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "T");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_coolantcontainer);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -117);
    lv_obj_set_y(ui_Label2, -50);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "C");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_coolantcontainer);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -117);
    lv_obj_set_y(ui_Label5, -20);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "L");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_coolantcontainer);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -117);
    lv_obj_set_y(ui_Label6, 10);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "N");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpscontainer = lv_obj_create(ui_Driver_Mode);
    lv_obj_remove_style_all(ui_gpscontainer);
    lv_obj_set_width(ui_gpscontainer, 129);
    lv_obj_set_height(ui_gpscontainer, 50);
    lv_obj_set_x(ui_gpscontainer, -52);
    lv_obj_set_y(ui_gpscontainer, 160);
    lv_obj_set_align(ui_gpscontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gpscontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_border_color(ui_gpscontainer, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gpscontainer, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_gpscontainer, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_maplabel = lv_label_create(ui_Driver_Mode);
    lv_obj_set_width(ui_maplabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_maplabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_maplabel, -300);
    lv_obj_set_y(ui_maplabel, 135);
    lv_obj_set_align(ui_maplabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_maplabel, "MAP");
    lv_obj_set_style_text_color(ui_maplabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_maplabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_maplabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_map = lv_label_create(ui_Driver_Mode);
    lv_obj_set_width(ui_map, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_map, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_map, -300);
    lv_obj_set_y(ui_map, 177);
    lv_obj_set_align(ui_map, LV_ALIGN_CENTER);
    lv_label_set_text(ui_map, "0");
    lv_obj_set_style_text_color(ui_map, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_map, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_map, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gforcelabel = lv_label_create(ui_Driver_Mode);
    lv_obj_set_width(ui_gforcelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gforcelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gforcelabel, -100);
    lv_obj_set_y(ui_gforcelabel, 135);
    lv_obj_set_align(ui_gforcelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gforcelabel, "G-FORCE");
    lv_obj_set_style_text_color(ui_gforcelabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gforcelabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gforcelabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gforce = lv_label_create(ui_Driver_Mode);
    lv_obj_set_width(ui_gforce, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gforce, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gforce, -100);
    lv_obj_set_y(ui_gforce, 180);
    lv_obj_set_align(ui_gforce, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gforce, "0");
    lv_obj_set_style_text_color(ui_gforce, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gforce, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gforce, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpslabel = lv_label_create(ui_Driver_Mode);
    lv_obj_set_width(ui_gpslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpslabel, 100);
    lv_obj_set_y(ui_gpslabel, 135);
    lv_obj_set_align(ui_gpslabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpslabel, "GPS SPD");
    lv_obj_set_style_text_color(ui_gpslabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpslabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpslabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gps = lv_label_create(ui_Driver_Mode);
    lv_obj_set_width(ui_gps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gps, 100);
    lv_obj_set_y(ui_gps, 180);
    lv_obj_set_align(ui_gps, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gps, "0");
    lv_obj_set_style_text_color(ui_gps, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gps, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltslabel = lv_label_create(ui_Driver_Mode);
    lv_obj_set_width(ui_voltslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voltslabel, 300);
    lv_obj_set_y(ui_voltslabel, 135);
    lv_obj_set_align(ui_voltslabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltslabel, "VOLTS");
    lv_obj_set_style_text_color(ui_voltslabel, lv_color_hex(0xF000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_voltslabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_voltslabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volts = lv_label_create(ui_Driver_Mode);
    lv_obj_set_width(ui_volts, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_volts, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_volts, 300);
    lv_obj_set_y(ui_volts, 180);
    lv_obj_set_align(ui_volts, LV_ALIGN_CENTER);
    lv_label_set_text(ui_volts, "0");
    lv_obj_set_style_text_color(ui_volts, lv_color_hex(0xF000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_volts, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_volts, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_engrbutton = lv_btn_create(ui_Driver_Mode);
    lv_obj_set_width(ui_engrbutton, 800);
    lv_obj_set_height(ui_engrbutton, 114);
    lv_obj_set_x(ui_engrbutton, 0);
    lv_obj_set_y(ui_engrbutton, 161);
    lv_obj_set_align(ui_engrbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_engrbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_engrbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_engrbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_engrbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_engrbutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_engrbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_engrbutton, ui_event_engrbutton, LV_EVENT_ALL, NULL);

}

void ui_Driver_Mode_screen_destroy(void)
{
    if(ui_Driver_Mode) lv_obj_del(ui_Driver_Mode);

    // NULL screen variables
    ui_Driver_Mode = NULL;
    ui_rpmbar = NULL;
    ui_battbar = NULL;
    ui_rpmcontainer = NULL;
    ui_rpm = NULL;
    ui_Label13 = NULL;
    ui_Label15 = NULL;
    ui_Label16 = NULL;
    ui_lightcontainer = NULL;
    ui_kill = NULL;
    ui_stall = NULL;
    ui_batt = NULL;
    ui_heat = NULL;
    ui_gearcontainer = NULL;
    ui_gear = NULL;
    ui_speedcontainer = NULL;
    ui_speed = NULL;
    ui_Label3 = NULL;
    ui_Label17 = NULL;
    ui_Label19 = NULL;
    ui_Label18 = NULL;
    ui_Label20 = NULL;
    ui_laptimercontainer = NULL;
    ui_laptimer = NULL;
    ui_coolantcontainer = NULL;
    ui_coolant = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_gpscontainer = NULL;
    ui_maplabel = NULL;
    ui_map = NULL;
    ui_gforcelabel = NULL;
    ui_gforce = NULL;
    ui_gpslabel = NULL;
    ui_gps = NULL;
    ui_voltslabel = NULL;
    ui_volts = NULL;
    ui_engrbutton = NULL;

}
