// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ENGINEER_MODE_H
#define UI_ENGINEER_MODE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Engineer_Mode
extern void ui_Engineer_Mode_screen_init(void);
extern void ui_Engineer_Mode_screen_destroy(void);
extern lv_obj_t * ui_Engineer_Mode;
extern void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Container8;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label25;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

