// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_START_MODE_H
#define UI_START_MODE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Start_Mode
extern void ui_Start_Mode_screen_init(void);
extern void ui_Start_Mode_screen_destroy(void);
extern lv_obj_t * ui_Start_Mode;
extern void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

